### ISSUE TITLE
The option "csrf_protection" does not exist.

### ISSUE THREAD

**Issue by davalb** [mathielen/sapoci#1]
Hi, I am currently trying out your library and I get this error when I create a formBuilder like this

    $formFactory = Forms::createFormFactory();
    $formBuilderFactory = new OciFormbuilderFactory($formFactory);
    $formBuilder = $formBuilderFactory->factor($ociBasket);

The error diaappears when I remove the csrf_protection option in the OciFormBuilderFactory line 66

    ->createNamedBuilder(null, FormType::class, $formData);

I am using this library not in a Symfony context.

**Comment by mathielen** [comment]
You can now instantiate the factory with the csrf option disabled:
`$formBuilderFactory = new OciFormbuilderFactory($formFactory, false);`
