### ISSUE TITLE
CSRF protection odd behavior

### ISSUE THREAD

**Issue by Thorry84** [mathielen/sapoci#4]
https://github.com/mathielen/sapoci/blob/4451dab27480d2258354e04ebf5a3701b7deb6d5/src/Mathielen/SapOci/OciFormbuilderFactory.php#L67

This behavior seems rather odd, if the variable csrfTokenEnabled is true-ish then CSRF gets disabled? 
Shouldn't it work the other way around?

**Comment by Thorry84** [comment]
If I might suggest a fix?

Don't add specific variables for all the different form options, just add an array parameter to the constructor which is passed to the formbuilder constructor for the options. That way you cover all cases, including CSRF. Otherwise you'll be adding options forever and even then it's a problem if someone uses custom form extensions.

**Comment by mathielen** [comment]
Hey @Thorry84,

you are absolutely right. I have fixed it with a defaultFormOptions array.

Thank you for noticing.
Markus
